galaxy_info:
  author: "Logout"
  description: "Logout of Hitachi Vantara Storage Array"
  company: "Private Company"
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: 2.9
  galaxy_tags: [ 'hitachi', 'rest' ]
  dependencies: []
